# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mcjetson/Work/Controls_2D_CUDA

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mcjetson/Work/Controls_2D_CUDA

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mcjetson/Work/Controls_2D_CUDA/CMakeFiles /home/mcjetson/Work/Controls_2D_CUDA/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mcjetson/Work/Controls_2D_CUDA/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Controls.app

# Build rule for target.
Controls.app: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Controls.app
.PHONY : Controls.app

# fast build rule for target.
Controls.app/fast:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/build
.PHONY : Controls.app/fast

Source/main.o: Source/main.cu.o

.PHONY : Source/main.o

# target to build an object file
Source/main.cu.o:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/Source/main.cu.o
.PHONY : Source/main.cu.o

Source/main.i: Source/main.cu.i

.PHONY : Source/main.i

# target to preprocess a source file
Source/main.cu.i:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/Source/main.cu.i
.PHONY : Source/main.cu.i

Source/main.s: Source/main.cu.s

.PHONY : Source/main.s

# target to generate assembly for a file
Source/main.cu.s:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/Source/main.cu.s
.PHONY : Source/main.cu.s

lib/GLFW/src/context.o: lib/GLFW/src/context.c.o

.PHONY : lib/GLFW/src/context.o

# target to build an object file
lib/GLFW/src/context.c.o:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/GLFW/src/context.c.o
.PHONY : lib/GLFW/src/context.c.o

lib/GLFW/src/context.i: lib/GLFW/src/context.c.i

.PHONY : lib/GLFW/src/context.i

# target to preprocess a source file
lib/GLFW/src/context.c.i:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/GLFW/src/context.c.i
.PHONY : lib/GLFW/src/context.c.i

lib/GLFW/src/context.s: lib/GLFW/src/context.c.s

.PHONY : lib/GLFW/src/context.s

# target to generate assembly for a file
lib/GLFW/src/context.c.s:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/GLFW/src/context.c.s
.PHONY : lib/GLFW/src/context.c.s

lib/GLFW/src/egl_context.o: lib/GLFW/src/egl_context.c.o

.PHONY : lib/GLFW/src/egl_context.o

# target to build an object file
lib/GLFW/src/egl_context.c.o:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/GLFW/src/egl_context.c.o
.PHONY : lib/GLFW/src/egl_context.c.o

lib/GLFW/src/egl_context.i: lib/GLFW/src/egl_context.c.i

.PHONY : lib/GLFW/src/egl_context.i

# target to preprocess a source file
lib/GLFW/src/egl_context.c.i:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/GLFW/src/egl_context.c.i
.PHONY : lib/GLFW/src/egl_context.c.i

lib/GLFW/src/egl_context.s: lib/GLFW/src/egl_context.c.s

.PHONY : lib/GLFW/src/egl_context.s

# target to generate assembly for a file
lib/GLFW/src/egl_context.c.s:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/GLFW/src/egl_context.c.s
.PHONY : lib/GLFW/src/egl_context.c.s

lib/GLFW/src/glx_context.o: lib/GLFW/src/glx_context.c.o

.PHONY : lib/GLFW/src/glx_context.o

# target to build an object file
lib/GLFW/src/glx_context.c.o:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/GLFW/src/glx_context.c.o
.PHONY : lib/GLFW/src/glx_context.c.o

lib/GLFW/src/glx_context.i: lib/GLFW/src/glx_context.c.i

.PHONY : lib/GLFW/src/glx_context.i

# target to preprocess a source file
lib/GLFW/src/glx_context.c.i:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/GLFW/src/glx_context.c.i
.PHONY : lib/GLFW/src/glx_context.c.i

lib/GLFW/src/glx_context.s: lib/GLFW/src/glx_context.c.s

.PHONY : lib/GLFW/src/glx_context.s

# target to generate assembly for a file
lib/GLFW/src/glx_context.c.s:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/GLFW/src/glx_context.c.s
.PHONY : lib/GLFW/src/glx_context.c.s

lib/GLFW/src/init.o: lib/GLFW/src/init.c.o

.PHONY : lib/GLFW/src/init.o

# target to build an object file
lib/GLFW/src/init.c.o:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/GLFW/src/init.c.o
.PHONY : lib/GLFW/src/init.c.o

lib/GLFW/src/init.i: lib/GLFW/src/init.c.i

.PHONY : lib/GLFW/src/init.i

# target to preprocess a source file
lib/GLFW/src/init.c.i:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/GLFW/src/init.c.i
.PHONY : lib/GLFW/src/init.c.i

lib/GLFW/src/init.s: lib/GLFW/src/init.c.s

.PHONY : lib/GLFW/src/init.s

# target to generate assembly for a file
lib/GLFW/src/init.c.s:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/GLFW/src/init.c.s
.PHONY : lib/GLFW/src/init.c.s

lib/GLFW/src/input.o: lib/GLFW/src/input.c.o

.PHONY : lib/GLFW/src/input.o

# target to build an object file
lib/GLFW/src/input.c.o:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/GLFW/src/input.c.o
.PHONY : lib/GLFW/src/input.c.o

lib/GLFW/src/input.i: lib/GLFW/src/input.c.i

.PHONY : lib/GLFW/src/input.i

# target to preprocess a source file
lib/GLFW/src/input.c.i:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/GLFW/src/input.c.i
.PHONY : lib/GLFW/src/input.c.i

lib/GLFW/src/input.s: lib/GLFW/src/input.c.s

.PHONY : lib/GLFW/src/input.s

# target to generate assembly for a file
lib/GLFW/src/input.c.s:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/GLFW/src/input.c.s
.PHONY : lib/GLFW/src/input.c.s

lib/GLFW/src/linux_joystick.o: lib/GLFW/src/linux_joystick.c.o

.PHONY : lib/GLFW/src/linux_joystick.o

# target to build an object file
lib/GLFW/src/linux_joystick.c.o:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/GLFW/src/linux_joystick.c.o
.PHONY : lib/GLFW/src/linux_joystick.c.o

lib/GLFW/src/linux_joystick.i: lib/GLFW/src/linux_joystick.c.i

.PHONY : lib/GLFW/src/linux_joystick.i

# target to preprocess a source file
lib/GLFW/src/linux_joystick.c.i:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/GLFW/src/linux_joystick.c.i
.PHONY : lib/GLFW/src/linux_joystick.c.i

lib/GLFW/src/linux_joystick.s: lib/GLFW/src/linux_joystick.c.s

.PHONY : lib/GLFW/src/linux_joystick.s

# target to generate assembly for a file
lib/GLFW/src/linux_joystick.c.s:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/GLFW/src/linux_joystick.c.s
.PHONY : lib/GLFW/src/linux_joystick.c.s

lib/GLFW/src/monitor.o: lib/GLFW/src/monitor.c.o

.PHONY : lib/GLFW/src/monitor.o

# target to build an object file
lib/GLFW/src/monitor.c.o:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/GLFW/src/monitor.c.o
.PHONY : lib/GLFW/src/monitor.c.o

lib/GLFW/src/monitor.i: lib/GLFW/src/monitor.c.i

.PHONY : lib/GLFW/src/monitor.i

# target to preprocess a source file
lib/GLFW/src/monitor.c.i:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/GLFW/src/monitor.c.i
.PHONY : lib/GLFW/src/monitor.c.i

lib/GLFW/src/monitor.s: lib/GLFW/src/monitor.c.s

.PHONY : lib/GLFW/src/monitor.s

# target to generate assembly for a file
lib/GLFW/src/monitor.c.s:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/GLFW/src/monitor.c.s
.PHONY : lib/GLFW/src/monitor.c.s

lib/GLFW/src/osmesa_context.o: lib/GLFW/src/osmesa_context.c.o

.PHONY : lib/GLFW/src/osmesa_context.o

# target to build an object file
lib/GLFW/src/osmesa_context.c.o:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/GLFW/src/osmesa_context.c.o
.PHONY : lib/GLFW/src/osmesa_context.c.o

lib/GLFW/src/osmesa_context.i: lib/GLFW/src/osmesa_context.c.i

.PHONY : lib/GLFW/src/osmesa_context.i

# target to preprocess a source file
lib/GLFW/src/osmesa_context.c.i:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/GLFW/src/osmesa_context.c.i
.PHONY : lib/GLFW/src/osmesa_context.c.i

lib/GLFW/src/osmesa_context.s: lib/GLFW/src/osmesa_context.c.s

.PHONY : lib/GLFW/src/osmesa_context.s

# target to generate assembly for a file
lib/GLFW/src/osmesa_context.c.s:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/GLFW/src/osmesa_context.c.s
.PHONY : lib/GLFW/src/osmesa_context.c.s

lib/GLFW/src/posix_thread.o: lib/GLFW/src/posix_thread.c.o

.PHONY : lib/GLFW/src/posix_thread.o

# target to build an object file
lib/GLFW/src/posix_thread.c.o:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/GLFW/src/posix_thread.c.o
.PHONY : lib/GLFW/src/posix_thread.c.o

lib/GLFW/src/posix_thread.i: lib/GLFW/src/posix_thread.c.i

.PHONY : lib/GLFW/src/posix_thread.i

# target to preprocess a source file
lib/GLFW/src/posix_thread.c.i:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/GLFW/src/posix_thread.c.i
.PHONY : lib/GLFW/src/posix_thread.c.i

lib/GLFW/src/posix_thread.s: lib/GLFW/src/posix_thread.c.s

.PHONY : lib/GLFW/src/posix_thread.s

# target to generate assembly for a file
lib/GLFW/src/posix_thread.c.s:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/GLFW/src/posix_thread.c.s
.PHONY : lib/GLFW/src/posix_thread.c.s

lib/GLFW/src/posix_time.o: lib/GLFW/src/posix_time.c.o

.PHONY : lib/GLFW/src/posix_time.o

# target to build an object file
lib/GLFW/src/posix_time.c.o:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/GLFW/src/posix_time.c.o
.PHONY : lib/GLFW/src/posix_time.c.o

lib/GLFW/src/posix_time.i: lib/GLFW/src/posix_time.c.i

.PHONY : lib/GLFW/src/posix_time.i

# target to preprocess a source file
lib/GLFW/src/posix_time.c.i:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/GLFW/src/posix_time.c.i
.PHONY : lib/GLFW/src/posix_time.c.i

lib/GLFW/src/posix_time.s: lib/GLFW/src/posix_time.c.s

.PHONY : lib/GLFW/src/posix_time.s

# target to generate assembly for a file
lib/GLFW/src/posix_time.c.s:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/GLFW/src/posix_time.c.s
.PHONY : lib/GLFW/src/posix_time.c.s

lib/GLFW/src/vulkan.o: lib/GLFW/src/vulkan.c.o

.PHONY : lib/GLFW/src/vulkan.o

# target to build an object file
lib/GLFW/src/vulkan.c.o:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/GLFW/src/vulkan.c.o
.PHONY : lib/GLFW/src/vulkan.c.o

lib/GLFW/src/vulkan.i: lib/GLFW/src/vulkan.c.i

.PHONY : lib/GLFW/src/vulkan.i

# target to preprocess a source file
lib/GLFW/src/vulkan.c.i:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/GLFW/src/vulkan.c.i
.PHONY : lib/GLFW/src/vulkan.c.i

lib/GLFW/src/vulkan.s: lib/GLFW/src/vulkan.c.s

.PHONY : lib/GLFW/src/vulkan.s

# target to generate assembly for a file
lib/GLFW/src/vulkan.c.s:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/GLFW/src/vulkan.c.s
.PHONY : lib/GLFW/src/vulkan.c.s

lib/GLFW/src/window.o: lib/GLFW/src/window.c.o

.PHONY : lib/GLFW/src/window.o

# target to build an object file
lib/GLFW/src/window.c.o:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/GLFW/src/window.c.o
.PHONY : lib/GLFW/src/window.c.o

lib/GLFW/src/window.i: lib/GLFW/src/window.c.i

.PHONY : lib/GLFW/src/window.i

# target to preprocess a source file
lib/GLFW/src/window.c.i:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/GLFW/src/window.c.i
.PHONY : lib/GLFW/src/window.c.i

lib/GLFW/src/window.s: lib/GLFW/src/window.c.s

.PHONY : lib/GLFW/src/window.s

# target to generate assembly for a file
lib/GLFW/src/window.c.s:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/GLFW/src/window.c.s
.PHONY : lib/GLFW/src/window.c.s

lib/GLFW/src/x11_init.o: lib/GLFW/src/x11_init.c.o

.PHONY : lib/GLFW/src/x11_init.o

# target to build an object file
lib/GLFW/src/x11_init.c.o:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/GLFW/src/x11_init.c.o
.PHONY : lib/GLFW/src/x11_init.c.o

lib/GLFW/src/x11_init.i: lib/GLFW/src/x11_init.c.i

.PHONY : lib/GLFW/src/x11_init.i

# target to preprocess a source file
lib/GLFW/src/x11_init.c.i:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/GLFW/src/x11_init.c.i
.PHONY : lib/GLFW/src/x11_init.c.i

lib/GLFW/src/x11_init.s: lib/GLFW/src/x11_init.c.s

.PHONY : lib/GLFW/src/x11_init.s

# target to generate assembly for a file
lib/GLFW/src/x11_init.c.s:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/GLFW/src/x11_init.c.s
.PHONY : lib/GLFW/src/x11_init.c.s

lib/GLFW/src/x11_monitor.o: lib/GLFW/src/x11_monitor.c.o

.PHONY : lib/GLFW/src/x11_monitor.o

# target to build an object file
lib/GLFW/src/x11_monitor.c.o:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/GLFW/src/x11_monitor.c.o
.PHONY : lib/GLFW/src/x11_monitor.c.o

lib/GLFW/src/x11_monitor.i: lib/GLFW/src/x11_monitor.c.i

.PHONY : lib/GLFW/src/x11_monitor.i

# target to preprocess a source file
lib/GLFW/src/x11_monitor.c.i:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/GLFW/src/x11_monitor.c.i
.PHONY : lib/GLFW/src/x11_monitor.c.i

lib/GLFW/src/x11_monitor.s: lib/GLFW/src/x11_monitor.c.s

.PHONY : lib/GLFW/src/x11_monitor.s

# target to generate assembly for a file
lib/GLFW/src/x11_monitor.c.s:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/GLFW/src/x11_monitor.c.s
.PHONY : lib/GLFW/src/x11_monitor.c.s

lib/GLFW/src/x11_window.o: lib/GLFW/src/x11_window.c.o

.PHONY : lib/GLFW/src/x11_window.o

# target to build an object file
lib/GLFW/src/x11_window.c.o:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/GLFW/src/x11_window.c.o
.PHONY : lib/GLFW/src/x11_window.c.o

lib/GLFW/src/x11_window.i: lib/GLFW/src/x11_window.c.i

.PHONY : lib/GLFW/src/x11_window.i

# target to preprocess a source file
lib/GLFW/src/x11_window.c.i:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/GLFW/src/x11_window.c.i
.PHONY : lib/GLFW/src/x11_window.c.i

lib/GLFW/src/x11_window.s: lib/GLFW/src/x11_window.c.s

.PHONY : lib/GLFW/src/x11_window.s

# target to generate assembly for a file
lib/GLFW/src/x11_window.c.s:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/GLFW/src/x11_window.c.s
.PHONY : lib/GLFW/src/x11_window.c.s

lib/GLFW/src/xkb_unicode.o: lib/GLFW/src/xkb_unicode.c.o

.PHONY : lib/GLFW/src/xkb_unicode.o

# target to build an object file
lib/GLFW/src/xkb_unicode.c.o:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/GLFW/src/xkb_unicode.c.o
.PHONY : lib/GLFW/src/xkb_unicode.c.o

lib/GLFW/src/xkb_unicode.i: lib/GLFW/src/xkb_unicode.c.i

.PHONY : lib/GLFW/src/xkb_unicode.i

# target to preprocess a source file
lib/GLFW/src/xkb_unicode.c.i:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/GLFW/src/xkb_unicode.c.i
.PHONY : lib/GLFW/src/xkb_unicode.c.i

lib/GLFW/src/xkb_unicode.s: lib/GLFW/src/xkb_unicode.c.s

.PHONY : lib/GLFW/src/xkb_unicode.s

# target to generate assembly for a file
lib/GLFW/src/xkb_unicode.c.s:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/GLFW/src/xkb_unicode.c.s
.PHONY : lib/GLFW/src/xkb_unicode.c.s

lib/glad/glad.o: lib/glad/glad.c.o

.PHONY : lib/glad/glad.o

# target to build an object file
lib/glad/glad.c.o:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/glad/glad.c.o
.PHONY : lib/glad/glad.c.o

lib/glad/glad.i: lib/glad/glad.c.i

.PHONY : lib/glad/glad.i

# target to preprocess a source file
lib/glad/glad.c.i:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/glad/glad.c.i
.PHONY : lib/glad/glad.c.i

lib/glad/glad.s: lib/glad/glad.c.s

.PHONY : lib/glad/glad.s

# target to generate assembly for a file
lib/glad/glad.c.s:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/glad/glad.c.s
.PHONY : lib/glad/glad.c.s

lib/imgui/imgui.o: lib/imgui/imgui.cpp.o

.PHONY : lib/imgui/imgui.o

# target to build an object file
lib/imgui/imgui.cpp.o:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/imgui/imgui.cpp.o
.PHONY : lib/imgui/imgui.cpp.o

lib/imgui/imgui.i: lib/imgui/imgui.cpp.i

.PHONY : lib/imgui/imgui.i

# target to preprocess a source file
lib/imgui/imgui.cpp.i:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/imgui/imgui.cpp.i
.PHONY : lib/imgui/imgui.cpp.i

lib/imgui/imgui.s: lib/imgui/imgui.cpp.s

.PHONY : lib/imgui/imgui.s

# target to generate assembly for a file
lib/imgui/imgui.cpp.s:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/imgui/imgui.cpp.s
.PHONY : lib/imgui/imgui.cpp.s

lib/imgui/imgui_draw.o: lib/imgui/imgui_draw.cpp.o

.PHONY : lib/imgui/imgui_draw.o

# target to build an object file
lib/imgui/imgui_draw.cpp.o:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/imgui/imgui_draw.cpp.o
.PHONY : lib/imgui/imgui_draw.cpp.o

lib/imgui/imgui_draw.i: lib/imgui/imgui_draw.cpp.i

.PHONY : lib/imgui/imgui_draw.i

# target to preprocess a source file
lib/imgui/imgui_draw.cpp.i:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/imgui/imgui_draw.cpp.i
.PHONY : lib/imgui/imgui_draw.cpp.i

lib/imgui/imgui_draw.s: lib/imgui/imgui_draw.cpp.s

.PHONY : lib/imgui/imgui_draw.s

# target to generate assembly for a file
lib/imgui/imgui_draw.cpp.s:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/imgui/imgui_draw.cpp.s
.PHONY : lib/imgui/imgui_draw.cpp.s

lib/imgui/imgui_impl_glfw.o: lib/imgui/imgui_impl_glfw.cpp.o

.PHONY : lib/imgui/imgui_impl_glfw.o

# target to build an object file
lib/imgui/imgui_impl_glfw.cpp.o:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/imgui/imgui_impl_glfw.cpp.o
.PHONY : lib/imgui/imgui_impl_glfw.cpp.o

lib/imgui/imgui_impl_glfw.i: lib/imgui/imgui_impl_glfw.cpp.i

.PHONY : lib/imgui/imgui_impl_glfw.i

# target to preprocess a source file
lib/imgui/imgui_impl_glfw.cpp.i:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/imgui/imgui_impl_glfw.cpp.i
.PHONY : lib/imgui/imgui_impl_glfw.cpp.i

lib/imgui/imgui_impl_glfw.s: lib/imgui/imgui_impl_glfw.cpp.s

.PHONY : lib/imgui/imgui_impl_glfw.s

# target to generate assembly for a file
lib/imgui/imgui_impl_glfw.cpp.s:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/imgui/imgui_impl_glfw.cpp.s
.PHONY : lib/imgui/imgui_impl_glfw.cpp.s

lib/imgui/imgui_impl_opengl3.o: lib/imgui/imgui_impl_opengl3.cpp.o

.PHONY : lib/imgui/imgui_impl_opengl3.o

# target to build an object file
lib/imgui/imgui_impl_opengl3.cpp.o:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/imgui/imgui_impl_opengl3.cpp.o
.PHONY : lib/imgui/imgui_impl_opengl3.cpp.o

lib/imgui/imgui_impl_opengl3.i: lib/imgui/imgui_impl_opengl3.cpp.i

.PHONY : lib/imgui/imgui_impl_opengl3.i

# target to preprocess a source file
lib/imgui/imgui_impl_opengl3.cpp.i:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/imgui/imgui_impl_opengl3.cpp.i
.PHONY : lib/imgui/imgui_impl_opengl3.cpp.i

lib/imgui/imgui_impl_opengl3.s: lib/imgui/imgui_impl_opengl3.cpp.s

.PHONY : lib/imgui/imgui_impl_opengl3.s

# target to generate assembly for a file
lib/imgui/imgui_impl_opengl3.cpp.s:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/imgui/imgui_impl_opengl3.cpp.s
.PHONY : lib/imgui/imgui_impl_opengl3.cpp.s

lib/imgui/imgui_widgets.o: lib/imgui/imgui_widgets.cpp.o

.PHONY : lib/imgui/imgui_widgets.o

# target to build an object file
lib/imgui/imgui_widgets.cpp.o:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/imgui/imgui_widgets.cpp.o
.PHONY : lib/imgui/imgui_widgets.cpp.o

lib/imgui/imgui_widgets.i: lib/imgui/imgui_widgets.cpp.i

.PHONY : lib/imgui/imgui_widgets.i

# target to preprocess a source file
lib/imgui/imgui_widgets.cpp.i:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/imgui/imgui_widgets.cpp.i
.PHONY : lib/imgui/imgui_widgets.cpp.i

lib/imgui/imgui_widgets.s: lib/imgui/imgui_widgets.cpp.s

.PHONY : lib/imgui/imgui_widgets.s

# target to generate assembly for a file
lib/imgui/imgui_widgets.cpp.s:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/imgui/imgui_widgets.cpp.s
.PHONY : lib/imgui/imgui_widgets.cpp.s

lib/qu3e/broadphase/q3BroadPhase.o: lib/qu3e/broadphase/q3BroadPhase.cpp.o

.PHONY : lib/qu3e/broadphase/q3BroadPhase.o

# target to build an object file
lib/qu3e/broadphase/q3BroadPhase.cpp.o:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/qu3e/broadphase/q3BroadPhase.cpp.o
.PHONY : lib/qu3e/broadphase/q3BroadPhase.cpp.o

lib/qu3e/broadphase/q3BroadPhase.i: lib/qu3e/broadphase/q3BroadPhase.cpp.i

.PHONY : lib/qu3e/broadphase/q3BroadPhase.i

# target to preprocess a source file
lib/qu3e/broadphase/q3BroadPhase.cpp.i:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/qu3e/broadphase/q3BroadPhase.cpp.i
.PHONY : lib/qu3e/broadphase/q3BroadPhase.cpp.i

lib/qu3e/broadphase/q3BroadPhase.s: lib/qu3e/broadphase/q3BroadPhase.cpp.s

.PHONY : lib/qu3e/broadphase/q3BroadPhase.s

# target to generate assembly for a file
lib/qu3e/broadphase/q3BroadPhase.cpp.s:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/qu3e/broadphase/q3BroadPhase.cpp.s
.PHONY : lib/qu3e/broadphase/q3BroadPhase.cpp.s

lib/qu3e/broadphase/q3DynamicAABBTree.o: lib/qu3e/broadphase/q3DynamicAABBTree.cpp.o

.PHONY : lib/qu3e/broadphase/q3DynamicAABBTree.o

# target to build an object file
lib/qu3e/broadphase/q3DynamicAABBTree.cpp.o:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/qu3e/broadphase/q3DynamicAABBTree.cpp.o
.PHONY : lib/qu3e/broadphase/q3DynamicAABBTree.cpp.o

lib/qu3e/broadphase/q3DynamicAABBTree.i: lib/qu3e/broadphase/q3DynamicAABBTree.cpp.i

.PHONY : lib/qu3e/broadphase/q3DynamicAABBTree.i

# target to preprocess a source file
lib/qu3e/broadphase/q3DynamicAABBTree.cpp.i:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/qu3e/broadphase/q3DynamicAABBTree.cpp.i
.PHONY : lib/qu3e/broadphase/q3DynamicAABBTree.cpp.i

lib/qu3e/broadphase/q3DynamicAABBTree.s: lib/qu3e/broadphase/q3DynamicAABBTree.cpp.s

.PHONY : lib/qu3e/broadphase/q3DynamicAABBTree.s

# target to generate assembly for a file
lib/qu3e/broadphase/q3DynamicAABBTree.cpp.s:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/qu3e/broadphase/q3DynamicAABBTree.cpp.s
.PHONY : lib/qu3e/broadphase/q3DynamicAABBTree.cpp.s

lib/qu3e/collision/q3Box.o: lib/qu3e/collision/q3Box.cpp.o

.PHONY : lib/qu3e/collision/q3Box.o

# target to build an object file
lib/qu3e/collision/q3Box.cpp.o:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/qu3e/collision/q3Box.cpp.o
.PHONY : lib/qu3e/collision/q3Box.cpp.o

lib/qu3e/collision/q3Box.i: lib/qu3e/collision/q3Box.cpp.i

.PHONY : lib/qu3e/collision/q3Box.i

# target to preprocess a source file
lib/qu3e/collision/q3Box.cpp.i:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/qu3e/collision/q3Box.cpp.i
.PHONY : lib/qu3e/collision/q3Box.cpp.i

lib/qu3e/collision/q3Box.s: lib/qu3e/collision/q3Box.cpp.s

.PHONY : lib/qu3e/collision/q3Box.s

# target to generate assembly for a file
lib/qu3e/collision/q3Box.cpp.s:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/qu3e/collision/q3Box.cpp.s
.PHONY : lib/qu3e/collision/q3Box.cpp.s

lib/qu3e/collision/q3Collide.o: lib/qu3e/collision/q3Collide.cpp.o

.PHONY : lib/qu3e/collision/q3Collide.o

# target to build an object file
lib/qu3e/collision/q3Collide.cpp.o:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/qu3e/collision/q3Collide.cpp.o
.PHONY : lib/qu3e/collision/q3Collide.cpp.o

lib/qu3e/collision/q3Collide.i: lib/qu3e/collision/q3Collide.cpp.i

.PHONY : lib/qu3e/collision/q3Collide.i

# target to preprocess a source file
lib/qu3e/collision/q3Collide.cpp.i:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/qu3e/collision/q3Collide.cpp.i
.PHONY : lib/qu3e/collision/q3Collide.cpp.i

lib/qu3e/collision/q3Collide.s: lib/qu3e/collision/q3Collide.cpp.s

.PHONY : lib/qu3e/collision/q3Collide.s

# target to generate assembly for a file
lib/qu3e/collision/q3Collide.cpp.s:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/qu3e/collision/q3Collide.cpp.s
.PHONY : lib/qu3e/collision/q3Collide.cpp.s

lib/qu3e/common/q3Geometry.o: lib/qu3e/common/q3Geometry.cpp.o

.PHONY : lib/qu3e/common/q3Geometry.o

# target to build an object file
lib/qu3e/common/q3Geometry.cpp.o:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/qu3e/common/q3Geometry.cpp.o
.PHONY : lib/qu3e/common/q3Geometry.cpp.o

lib/qu3e/common/q3Geometry.i: lib/qu3e/common/q3Geometry.cpp.i

.PHONY : lib/qu3e/common/q3Geometry.i

# target to preprocess a source file
lib/qu3e/common/q3Geometry.cpp.i:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/qu3e/common/q3Geometry.cpp.i
.PHONY : lib/qu3e/common/q3Geometry.cpp.i

lib/qu3e/common/q3Geometry.s: lib/qu3e/common/q3Geometry.cpp.s

.PHONY : lib/qu3e/common/q3Geometry.s

# target to generate assembly for a file
lib/qu3e/common/q3Geometry.cpp.s:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/qu3e/common/q3Geometry.cpp.s
.PHONY : lib/qu3e/common/q3Geometry.cpp.s

lib/qu3e/common/q3Memory.o: lib/qu3e/common/q3Memory.cpp.o

.PHONY : lib/qu3e/common/q3Memory.o

# target to build an object file
lib/qu3e/common/q3Memory.cpp.o:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/qu3e/common/q3Memory.cpp.o
.PHONY : lib/qu3e/common/q3Memory.cpp.o

lib/qu3e/common/q3Memory.i: lib/qu3e/common/q3Memory.cpp.i

.PHONY : lib/qu3e/common/q3Memory.i

# target to preprocess a source file
lib/qu3e/common/q3Memory.cpp.i:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/qu3e/common/q3Memory.cpp.i
.PHONY : lib/qu3e/common/q3Memory.cpp.i

lib/qu3e/common/q3Memory.s: lib/qu3e/common/q3Memory.cpp.s

.PHONY : lib/qu3e/common/q3Memory.s

# target to generate assembly for a file
lib/qu3e/common/q3Memory.cpp.s:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/qu3e/common/q3Memory.cpp.s
.PHONY : lib/qu3e/common/q3Memory.cpp.s

lib/qu3e/dynamics/q3Body.o: lib/qu3e/dynamics/q3Body.cpp.o

.PHONY : lib/qu3e/dynamics/q3Body.o

# target to build an object file
lib/qu3e/dynamics/q3Body.cpp.o:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/qu3e/dynamics/q3Body.cpp.o
.PHONY : lib/qu3e/dynamics/q3Body.cpp.o

lib/qu3e/dynamics/q3Body.i: lib/qu3e/dynamics/q3Body.cpp.i

.PHONY : lib/qu3e/dynamics/q3Body.i

# target to preprocess a source file
lib/qu3e/dynamics/q3Body.cpp.i:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/qu3e/dynamics/q3Body.cpp.i
.PHONY : lib/qu3e/dynamics/q3Body.cpp.i

lib/qu3e/dynamics/q3Body.s: lib/qu3e/dynamics/q3Body.cpp.s

.PHONY : lib/qu3e/dynamics/q3Body.s

# target to generate assembly for a file
lib/qu3e/dynamics/q3Body.cpp.s:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/qu3e/dynamics/q3Body.cpp.s
.PHONY : lib/qu3e/dynamics/q3Body.cpp.s

lib/qu3e/dynamics/q3Contact.o: lib/qu3e/dynamics/q3Contact.cpp.o

.PHONY : lib/qu3e/dynamics/q3Contact.o

# target to build an object file
lib/qu3e/dynamics/q3Contact.cpp.o:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/qu3e/dynamics/q3Contact.cpp.o
.PHONY : lib/qu3e/dynamics/q3Contact.cpp.o

lib/qu3e/dynamics/q3Contact.i: lib/qu3e/dynamics/q3Contact.cpp.i

.PHONY : lib/qu3e/dynamics/q3Contact.i

# target to preprocess a source file
lib/qu3e/dynamics/q3Contact.cpp.i:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/qu3e/dynamics/q3Contact.cpp.i
.PHONY : lib/qu3e/dynamics/q3Contact.cpp.i

lib/qu3e/dynamics/q3Contact.s: lib/qu3e/dynamics/q3Contact.cpp.s

.PHONY : lib/qu3e/dynamics/q3Contact.s

# target to generate assembly for a file
lib/qu3e/dynamics/q3Contact.cpp.s:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/qu3e/dynamics/q3Contact.cpp.s
.PHONY : lib/qu3e/dynamics/q3Contact.cpp.s

lib/qu3e/dynamics/q3ContactManager.o: lib/qu3e/dynamics/q3ContactManager.cpp.o

.PHONY : lib/qu3e/dynamics/q3ContactManager.o

# target to build an object file
lib/qu3e/dynamics/q3ContactManager.cpp.o:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/qu3e/dynamics/q3ContactManager.cpp.o
.PHONY : lib/qu3e/dynamics/q3ContactManager.cpp.o

lib/qu3e/dynamics/q3ContactManager.i: lib/qu3e/dynamics/q3ContactManager.cpp.i

.PHONY : lib/qu3e/dynamics/q3ContactManager.i

# target to preprocess a source file
lib/qu3e/dynamics/q3ContactManager.cpp.i:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/qu3e/dynamics/q3ContactManager.cpp.i
.PHONY : lib/qu3e/dynamics/q3ContactManager.cpp.i

lib/qu3e/dynamics/q3ContactManager.s: lib/qu3e/dynamics/q3ContactManager.cpp.s

.PHONY : lib/qu3e/dynamics/q3ContactManager.s

# target to generate assembly for a file
lib/qu3e/dynamics/q3ContactManager.cpp.s:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/qu3e/dynamics/q3ContactManager.cpp.s
.PHONY : lib/qu3e/dynamics/q3ContactManager.cpp.s

lib/qu3e/dynamics/q3ContactSolver.o: lib/qu3e/dynamics/q3ContactSolver.cpp.o

.PHONY : lib/qu3e/dynamics/q3ContactSolver.o

# target to build an object file
lib/qu3e/dynamics/q3ContactSolver.cpp.o:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/qu3e/dynamics/q3ContactSolver.cpp.o
.PHONY : lib/qu3e/dynamics/q3ContactSolver.cpp.o

lib/qu3e/dynamics/q3ContactSolver.i: lib/qu3e/dynamics/q3ContactSolver.cpp.i

.PHONY : lib/qu3e/dynamics/q3ContactSolver.i

# target to preprocess a source file
lib/qu3e/dynamics/q3ContactSolver.cpp.i:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/qu3e/dynamics/q3ContactSolver.cpp.i
.PHONY : lib/qu3e/dynamics/q3ContactSolver.cpp.i

lib/qu3e/dynamics/q3ContactSolver.s: lib/qu3e/dynamics/q3ContactSolver.cpp.s

.PHONY : lib/qu3e/dynamics/q3ContactSolver.s

# target to generate assembly for a file
lib/qu3e/dynamics/q3ContactSolver.cpp.s:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/qu3e/dynamics/q3ContactSolver.cpp.s
.PHONY : lib/qu3e/dynamics/q3ContactSolver.cpp.s

lib/qu3e/dynamics/q3Island.o: lib/qu3e/dynamics/q3Island.cpp.o

.PHONY : lib/qu3e/dynamics/q3Island.o

# target to build an object file
lib/qu3e/dynamics/q3Island.cpp.o:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/qu3e/dynamics/q3Island.cpp.o
.PHONY : lib/qu3e/dynamics/q3Island.cpp.o

lib/qu3e/dynamics/q3Island.i: lib/qu3e/dynamics/q3Island.cpp.i

.PHONY : lib/qu3e/dynamics/q3Island.i

# target to preprocess a source file
lib/qu3e/dynamics/q3Island.cpp.i:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/qu3e/dynamics/q3Island.cpp.i
.PHONY : lib/qu3e/dynamics/q3Island.cpp.i

lib/qu3e/dynamics/q3Island.s: lib/qu3e/dynamics/q3Island.cpp.s

.PHONY : lib/qu3e/dynamics/q3Island.s

# target to generate assembly for a file
lib/qu3e/dynamics/q3Island.cpp.s:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/qu3e/dynamics/q3Island.cpp.s
.PHONY : lib/qu3e/dynamics/q3Island.cpp.s

lib/qu3e/math/q3Mat3.o: lib/qu3e/math/q3Mat3.cpp.o

.PHONY : lib/qu3e/math/q3Mat3.o

# target to build an object file
lib/qu3e/math/q3Mat3.cpp.o:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/qu3e/math/q3Mat3.cpp.o
.PHONY : lib/qu3e/math/q3Mat3.cpp.o

lib/qu3e/math/q3Mat3.i: lib/qu3e/math/q3Mat3.cpp.i

.PHONY : lib/qu3e/math/q3Mat3.i

# target to preprocess a source file
lib/qu3e/math/q3Mat3.cpp.i:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/qu3e/math/q3Mat3.cpp.i
.PHONY : lib/qu3e/math/q3Mat3.cpp.i

lib/qu3e/math/q3Mat3.s: lib/qu3e/math/q3Mat3.cpp.s

.PHONY : lib/qu3e/math/q3Mat3.s

# target to generate assembly for a file
lib/qu3e/math/q3Mat3.cpp.s:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/qu3e/math/q3Mat3.cpp.s
.PHONY : lib/qu3e/math/q3Mat3.cpp.s

lib/qu3e/math/q3Quaternion.o: lib/qu3e/math/q3Quaternion.cpp.o

.PHONY : lib/qu3e/math/q3Quaternion.o

# target to build an object file
lib/qu3e/math/q3Quaternion.cpp.o:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/qu3e/math/q3Quaternion.cpp.o
.PHONY : lib/qu3e/math/q3Quaternion.cpp.o

lib/qu3e/math/q3Quaternion.i: lib/qu3e/math/q3Quaternion.cpp.i

.PHONY : lib/qu3e/math/q3Quaternion.i

# target to preprocess a source file
lib/qu3e/math/q3Quaternion.cpp.i:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/qu3e/math/q3Quaternion.cpp.i
.PHONY : lib/qu3e/math/q3Quaternion.cpp.i

lib/qu3e/math/q3Quaternion.s: lib/qu3e/math/q3Quaternion.cpp.s

.PHONY : lib/qu3e/math/q3Quaternion.s

# target to generate assembly for a file
lib/qu3e/math/q3Quaternion.cpp.s:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/qu3e/math/q3Quaternion.cpp.s
.PHONY : lib/qu3e/math/q3Quaternion.cpp.s

lib/qu3e/math/q3Vec3.o: lib/qu3e/math/q3Vec3.cpp.o

.PHONY : lib/qu3e/math/q3Vec3.o

# target to build an object file
lib/qu3e/math/q3Vec3.cpp.o:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/qu3e/math/q3Vec3.cpp.o
.PHONY : lib/qu3e/math/q3Vec3.cpp.o

lib/qu3e/math/q3Vec3.i: lib/qu3e/math/q3Vec3.cpp.i

.PHONY : lib/qu3e/math/q3Vec3.i

# target to preprocess a source file
lib/qu3e/math/q3Vec3.cpp.i:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/qu3e/math/q3Vec3.cpp.i
.PHONY : lib/qu3e/math/q3Vec3.cpp.i

lib/qu3e/math/q3Vec3.s: lib/qu3e/math/q3Vec3.cpp.s

.PHONY : lib/qu3e/math/q3Vec3.s

# target to generate assembly for a file
lib/qu3e/math/q3Vec3.cpp.s:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/qu3e/math/q3Vec3.cpp.s
.PHONY : lib/qu3e/math/q3Vec3.cpp.s

lib/qu3e/scene/q3Scene.o: lib/qu3e/scene/q3Scene.cpp.o

.PHONY : lib/qu3e/scene/q3Scene.o

# target to build an object file
lib/qu3e/scene/q3Scene.cpp.o:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/qu3e/scene/q3Scene.cpp.o
.PHONY : lib/qu3e/scene/q3Scene.cpp.o

lib/qu3e/scene/q3Scene.i: lib/qu3e/scene/q3Scene.cpp.i

.PHONY : lib/qu3e/scene/q3Scene.i

# target to preprocess a source file
lib/qu3e/scene/q3Scene.cpp.i:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/qu3e/scene/q3Scene.cpp.i
.PHONY : lib/qu3e/scene/q3Scene.cpp.i

lib/qu3e/scene/q3Scene.s: lib/qu3e/scene/q3Scene.cpp.s

.PHONY : lib/qu3e/scene/q3Scene.s

# target to generate assembly for a file
lib/qu3e/scene/q3Scene.cpp.s:
	$(MAKE) -f CMakeFiles/Controls.app.dir/build.make CMakeFiles/Controls.app.dir/lib/qu3e/scene/q3Scene.cpp.s
.PHONY : lib/qu3e/scene/q3Scene.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... Controls.app"
	@echo "... edit_cache"
	@echo "... Source/main.o"
	@echo "... Source/main.i"
	@echo "... Source/main.s"
	@echo "... lib/GLFW/src/context.o"
	@echo "... lib/GLFW/src/context.i"
	@echo "... lib/GLFW/src/context.s"
	@echo "... lib/GLFW/src/egl_context.o"
	@echo "... lib/GLFW/src/egl_context.i"
	@echo "... lib/GLFW/src/egl_context.s"
	@echo "... lib/GLFW/src/glx_context.o"
	@echo "... lib/GLFW/src/glx_context.i"
	@echo "... lib/GLFW/src/glx_context.s"
	@echo "... lib/GLFW/src/init.o"
	@echo "... lib/GLFW/src/init.i"
	@echo "... lib/GLFW/src/init.s"
	@echo "... lib/GLFW/src/input.o"
	@echo "... lib/GLFW/src/input.i"
	@echo "... lib/GLFW/src/input.s"
	@echo "... lib/GLFW/src/linux_joystick.o"
	@echo "... lib/GLFW/src/linux_joystick.i"
	@echo "... lib/GLFW/src/linux_joystick.s"
	@echo "... lib/GLFW/src/monitor.o"
	@echo "... lib/GLFW/src/monitor.i"
	@echo "... lib/GLFW/src/monitor.s"
	@echo "... lib/GLFW/src/osmesa_context.o"
	@echo "... lib/GLFW/src/osmesa_context.i"
	@echo "... lib/GLFW/src/osmesa_context.s"
	@echo "... lib/GLFW/src/posix_thread.o"
	@echo "... lib/GLFW/src/posix_thread.i"
	@echo "... lib/GLFW/src/posix_thread.s"
	@echo "... lib/GLFW/src/posix_time.o"
	@echo "... lib/GLFW/src/posix_time.i"
	@echo "... lib/GLFW/src/posix_time.s"
	@echo "... lib/GLFW/src/vulkan.o"
	@echo "... lib/GLFW/src/vulkan.i"
	@echo "... lib/GLFW/src/vulkan.s"
	@echo "... lib/GLFW/src/window.o"
	@echo "... lib/GLFW/src/window.i"
	@echo "... lib/GLFW/src/window.s"
	@echo "... lib/GLFW/src/x11_init.o"
	@echo "... lib/GLFW/src/x11_init.i"
	@echo "... lib/GLFW/src/x11_init.s"
	@echo "... lib/GLFW/src/x11_monitor.o"
	@echo "... lib/GLFW/src/x11_monitor.i"
	@echo "... lib/GLFW/src/x11_monitor.s"
	@echo "... lib/GLFW/src/x11_window.o"
	@echo "... lib/GLFW/src/x11_window.i"
	@echo "... lib/GLFW/src/x11_window.s"
	@echo "... lib/GLFW/src/xkb_unicode.o"
	@echo "... lib/GLFW/src/xkb_unicode.i"
	@echo "... lib/GLFW/src/xkb_unicode.s"
	@echo "... lib/glad/glad.o"
	@echo "... lib/glad/glad.i"
	@echo "... lib/glad/glad.s"
	@echo "... lib/imgui/imgui.o"
	@echo "... lib/imgui/imgui.i"
	@echo "... lib/imgui/imgui.s"
	@echo "... lib/imgui/imgui_draw.o"
	@echo "... lib/imgui/imgui_draw.i"
	@echo "... lib/imgui/imgui_draw.s"
	@echo "... lib/imgui/imgui_impl_glfw.o"
	@echo "... lib/imgui/imgui_impl_glfw.i"
	@echo "... lib/imgui/imgui_impl_glfw.s"
	@echo "... lib/imgui/imgui_impl_opengl3.o"
	@echo "... lib/imgui/imgui_impl_opengl3.i"
	@echo "... lib/imgui/imgui_impl_opengl3.s"
	@echo "... lib/imgui/imgui_widgets.o"
	@echo "... lib/imgui/imgui_widgets.i"
	@echo "... lib/imgui/imgui_widgets.s"
	@echo "... lib/qu3e/broadphase/q3BroadPhase.o"
	@echo "... lib/qu3e/broadphase/q3BroadPhase.i"
	@echo "... lib/qu3e/broadphase/q3BroadPhase.s"
	@echo "... lib/qu3e/broadphase/q3DynamicAABBTree.o"
	@echo "... lib/qu3e/broadphase/q3DynamicAABBTree.i"
	@echo "... lib/qu3e/broadphase/q3DynamicAABBTree.s"
	@echo "... lib/qu3e/collision/q3Box.o"
	@echo "... lib/qu3e/collision/q3Box.i"
	@echo "... lib/qu3e/collision/q3Box.s"
	@echo "... lib/qu3e/collision/q3Collide.o"
	@echo "... lib/qu3e/collision/q3Collide.i"
	@echo "... lib/qu3e/collision/q3Collide.s"
	@echo "... lib/qu3e/common/q3Geometry.o"
	@echo "... lib/qu3e/common/q3Geometry.i"
	@echo "... lib/qu3e/common/q3Geometry.s"
	@echo "... lib/qu3e/common/q3Memory.o"
	@echo "... lib/qu3e/common/q3Memory.i"
	@echo "... lib/qu3e/common/q3Memory.s"
	@echo "... lib/qu3e/dynamics/q3Body.o"
	@echo "... lib/qu3e/dynamics/q3Body.i"
	@echo "... lib/qu3e/dynamics/q3Body.s"
	@echo "... lib/qu3e/dynamics/q3Contact.o"
	@echo "... lib/qu3e/dynamics/q3Contact.i"
	@echo "... lib/qu3e/dynamics/q3Contact.s"
	@echo "... lib/qu3e/dynamics/q3ContactManager.o"
	@echo "... lib/qu3e/dynamics/q3ContactManager.i"
	@echo "... lib/qu3e/dynamics/q3ContactManager.s"
	@echo "... lib/qu3e/dynamics/q3ContactSolver.o"
	@echo "... lib/qu3e/dynamics/q3ContactSolver.i"
	@echo "... lib/qu3e/dynamics/q3ContactSolver.s"
	@echo "... lib/qu3e/dynamics/q3Island.o"
	@echo "... lib/qu3e/dynamics/q3Island.i"
	@echo "... lib/qu3e/dynamics/q3Island.s"
	@echo "... lib/qu3e/math/q3Mat3.o"
	@echo "... lib/qu3e/math/q3Mat3.i"
	@echo "... lib/qu3e/math/q3Mat3.s"
	@echo "... lib/qu3e/math/q3Quaternion.o"
	@echo "... lib/qu3e/math/q3Quaternion.i"
	@echo "... lib/qu3e/math/q3Quaternion.s"
	@echo "... lib/qu3e/math/q3Vec3.o"
	@echo "... lib/qu3e/math/q3Vec3.i"
	@echo "... lib/qu3e/math/q3Vec3.s"
	@echo "... lib/qu3e/scene/q3Scene.o"
	@echo "... lib/qu3e/scene/q3Scene.i"
	@echo "... lib/qu3e/scene/q3Scene.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

